spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s
      cluster-name: elasticsearch
file:
  server:
    url: http://localhost:8081/upload